# Jekyll configuration

name: Strange times
email: floriankopp@posteo.de
description: >- # this means to ignore newlines until "baseurl:"
  A software developer with psychology degree. Interested in science, well-being and weirdness. Here you find micro-bloggings about what I am up to and happen upon from all the perspectives I have to offer.
# Url is currently only used only for the RSS feed in feed.xml
url: http://fkopp81.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: ''

author: Florian Kopp
copyright: 2018

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  github: fkopp81
  stackoverflow: ''
  linkedin:
  instagram: ''
  lastfm: ''
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: fkopp81
comments: false

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "tag"
    values:
      layout: "tag_index"

prose:
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          value: ""
          label: "title"
      - name: "tags"
        field:
          element: "text"
          value: ""
          label: "tags"
      - name: "Date"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
    tag:
      - name: "tag"
        field:
         element: "text"
         value: ""
         label: "tag"
         